

// export const projectsData: Project[] = [
  // {
  //   title: 'E-Commerce Platform',
  //   description: 'A full-stack e-commerce platform with real-time inventory management',
  //   image: 'https://images.unsplash.com/photo-1557821552-17105176677c?w=800&h=450&fit=crop',
  //   category: 'web',
  //   technologies: ['Next.js', 'TypeScript', 'Prisma', 'Stripe'],
  //   github: 'https://github.com',
  //   demo: 'https://demo.com',
  // },
  // {
  //   title: 'Space Explorer Game',
  //   description: 'A 3D space exploration game with procedural generation',
  //   image: 'https://images.unsplash.com/photo-1614732414444-096e5f1122d5?w=800&h=450&fit=crop',
  //   category: 'game',
  //   technologies: ['Unity', 'C#', 'Blender'],
  //   github: 'https://github.com',
  //   demo: 'https://demo.com',
  // },
  // {
  //   title: 'Cloud Cost Optimizer',
  //   description: 'An automated cloud cost optimization solution for AWS',
  //   image: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=800&h=450&fit=crop',
  //   category: 'cloud',
  //   technologies: ['Python', 'AWS Lambda', 'DynamoDB'],
  //   github: 'https://github.com',
  //   demo: 'https://demo.com',
  // },
  // {
  //   title: 'Social Media Dashboard',
  //   description: 'Real-time analytics dashboard for social media management',
  //   image: 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&h=450&fit=crop',
  //   category: 'web',
  //   technologies: ['React', 'Redux', 'Node.js', 'MongoDB'],
  //   github: 'https://github.com',
  //   demo: 'https://demo.com',
  // },
  // {
  //   title: 'AR Puzzle Game',
  //   description: 'Augmented reality puzzle game for mobile devices',
  //   image: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?w=800&h=450&fit=crop',
  //   category: 'game',
  //   technologies: ['Unity', 'ARKit', 'ARCore'],
  //   github: 'https://github.com',
  //   demo: 'https://demo.com',
  // },
  // {
  //   title: 'Serverless CMS',
  //   description: 'A headless CMS built with serverless architecture',
  //   image: 'https://images.unsplash.com/photo-1667372393119-3d4c48d07fc9?w=800&h=450&fit=crop',
  //   category: 'cloud',
  //   technologies: ['AWS', 'Next.js', 'GraphQL'],
  //   github: 'https://github.com',
  //   demo: 'https://demo.com',
  // },
// ];